### ISSUE TITLE
Missing texture by 1.15.2

### ISSUE THREAD

**Issue by xinshuowl** [team-abnormals/upgrade-aquatic#210]
[minecraft/AtlasTexture]: Using missing texture, unable to load upgrade_aquatic:textures/item/bucket/jellyfish_bucket_immortal.png : java.io.FileNotFoundException: upgrade_aquatic:textures/item/bucket/jellyfish_bucket_immortal.png

**Comment by bageldotjpg** [comment]
1.15.2 is no longer supported, and this will not affect your gameplay
