### ISSUE TITLE
Memory leak when breaking prismarine coral

### ISSUE THREAD

**Issue by EightBlade** [team-abnormals/upgrade-aquatic#218]
It's as the title says, when trying to break the coral the game will spin it's wheels and eat up memory until it's unplayable. Here's a screenshot of the log when that happens.

https://imgur.com/e1UFdq8

**Comment by SmellyModder** [comment]
What version of the mod are you playing?

**Comment by EightBlade** [comment]
1.15.2-v1.7.1

**Comment by SmellyModder** [comment]
1.15.2 versions of Upgrade Aquatic are no longer supported, and this issue no longer exists in 1.16.1+ versions of Upgrade Aquatic.
