### ISSUE TITLE
[1.16.1] Prismarine stairs, slabs, and walls can no longer be used to power a conduit

### ISSUE THREAD

**Issue by EltrutLikes** [team-abnormals/upgrade-aquatic#219]
Previously, prismarine stairs, slabs, and walls were a part of the `forge:supports_conduit` block tag. This tag was eventually replaced in 6b06bf6 with the method `isConduitFrame` but that commit dropped support for stairs, slabs, and walls made of prismarine materials.

**Comment by SmellyModder** [comment]
This was intentional.
And there's no need to put [1.16.1] in the title of an issue since it's currently the only publicly supported version of UA.
For beta issues, report them in the discord server.
