### ISSUE TITLE
[1.16.4] - v3.0.0 - Quark mod loading error when Blossom Trees are disabled

### ISSUE THREAD

**Issue by clootas** [team-abnormals/upgrade-aquatic#227]
https://pastebin.com/s74MXYnm

The Blossom Trees feature from Quark must be enabled in order for Upgrade Aquatic to work. There's no mod loading error when it's enabled.

**Comment by bageldotjpg** [comment]
I don't think this relates to Upgrade Aquatic at all. Remove Upgrade Aquatic and try enabling and disabling blossom trees

**Comment by bageldotjpg** [comment]
I'm currently using Quark with Blossom Trees disabled and Upgrade Aquatic and they work just fine.
Make sure you're not making typos in your config.
