### ISSUE TITLE
[1.16.4] Impossible to interact when Ink Sac in hand

### ISSUE THREAD

**Issue by drakray** [team-abnormals/upgrade-aquatic#229]
As it says on the tin, with an Ink Sac in hand, it's not possible to open chest, place InkSac on M&A ritual chalk, sleep, open door, I think simply interacting with TileEntities become impossible.
Placing in an Item Frame work though, even though it's en entity.

**Comment by drakray** [comment]
It should also be configurable to be able to be disabled, I think

**Comment by ewsmith** [comment]
also got same issue here. can't do any m&a ritual that needs ink; one of which is needed for a progression branch. i just blind myself.
