### ISSUE TITLE
Quark Driftwood Chests Not Craftable

### ISSUE THREAD

**Issue by Nimflora** [team-abnormals/upgrade-aquatic#230]
It produces vanilla chests. Vazkii of Quark claims they stopped making it on their end and that it must be on this end.

**Comment by bageldotjpg** [comment]
Vazkii replaces the vanilla chest recipes to fix this so we unfortunately can't fix this without doing that as well causing all other chests to suffer from this issue
But, you can install the Polymorph mod to prevent recipe conflicts
