### ISSUE TITLE
[1.16.4_3.0.0] Way too many Pike spawning at rivers

### ISSUE THREAD

**Issue by MasterGoodbytes** [team-abnormals/upgrade-aquatic#232]
Pike start spawning excessively in river biomes after a few minutes, killing all other types of fish, and once it starts it looks like they spawn faster.
with the kill command, I could kill more than 300 of them in one place after less than 5 minutes.
![image](https://user-images.githubusercontent.com/76782647/103953347-e0b6e380-5139-11eb-954a-982ad526fe78.png)
![image](https://user-images.githubusercontent.com/76782647/103953370-e90f1e80-5139-11eb-881c-24e8deee7de9.png)

**Comment by Corvus20** [comment]
Can confirm this also happens in lakes as well.
![2021-01-08_10 27 22](https://user-images.githubusercontent.com/75586106/104033614-c31b6580-519d-11eb-9dd9-14fc908c8208.png)
![2021-01-08_10 31 38](https://user-images.githubusercontent.com/75586106/104033618-c3b3fc00-519d-11eb-86eb-34edd9b83a0b.png)
![2021-01-08_10 31 44](https://user-images.githubusercontent.com/75586106/104033619-c3b3fc00-519d-11eb-89fb-b1a05a56e301.png)

**Comment by bageldotjpg** [comment]
This has been fixed in dev and will be hopefully released soonish, when more bug fixes are complete
