### ISSUE TITLE
Occasional Crash when loading a world

### ISSUE THREAD

**Issue by Ritzumi** [team-abnormals/upgrade-aquatic#236]
### Versions
Forge: 35.1.36
Abnormals_Core: 1.16.4-3.0.6
Upgrade_Aquatic: 1.16.4-3.0.0

### Description
I encountered this crash occasionally when joining a world for the first time or loading a save (I put occasional because most of the time it didn't happen). Just joining the world would make the game crash and produce crash log. However, the world isn't corrupted. I can join it again after crash and most of the times it would run normally.

### Step to reproduce
Just load the world and it will crash sometime.
I can load it normally on second attempt.

### Attachment
Crash log: https://gist.github.com/Ritzumi/696648886feecd6399da64527a74deac
Log: https://gist.github.com/Ritzumi/2a264085dcdb60855212d9e3aa99466c
https://github.com/team-abnormals/abnormals-core/issues/66

**Comment by SmellyModder** [comment]
I did a bit more research, and this appears to be an issue with Reliquary.
There are also more conflicts like this due to Reliquary creating an entity too early.
This issue is similar: https://github.com/SilentChaos512/ScalingHealth/issues/295
