### ISSUE TITLE
Too many Thrashers [1.16.5 - 3.0.1]

### ISSUE THREAD

**Issue by KingThiccolo** [team-abnormals/upgrade-aquatic#240]
There are way too many thrashers spawning in the cold ocean in my world. They're killing all the fish and causing lag. Any help would be much appreciated

![Minecraft_ 1 16 5 - Singleplayer 1_27_2021 2_34_23 PM](https://user-images.githubusercontent.com/78107314/106043745-d8a0f280-60ac-11eb-8599-144240a6b626.png)

**Comment by InfinitysDaughter** [comment]
Heh. I'm having the exact opposite problem! Not a single one of the big hostile beasts have spawned naturally for me. Adding some spawn options to the config file would help.

**Comment by Tiln1** [comment]
I'm having a... tangential problem, which might explain InfinitysDaughter's problem. They are spawning at a decent rate AFAICT but they are all invisible and seem to have no hurt boxes, resulting in me getting shaken to death repeatedly. Their sonar shows up but they don't even show up with F3+b(though the sonar does). Playing on the Valhesia 3 modpack, multiplayer, though I can't find any thrashers, invisible nor visible in singleplayer. (Upgrade Aquatic 3.0.1, Abnormals Core 3.0.6).

**Comment by InfinitysDaughter** [comment]
That may be my problem, Tiln1. I'm developing a pack myself so I've been in creative making sure things spawn or work properly. If they are there but invisible then I wouldn't know. Though if they attack other aquatic mobs I havn't seen any sonar attacks.

**Comment by Vaelzan** [comment]
> I'm having a... tangential problem, which might explain InfinitysDaughter's problem. They are spawning at a decent rate AFAICT but they are all invisible and seem to have no hurt boxes, resulting in me getting shaken to death repeatedly. Their sonar shows up but they don't even show up with F3+b(though the sonar does). Playing on the Valhesia 3 modpack, multiplayer, though I can't find any thrashers, invisible nor visible in singleplayer. (Upgrade Aquatic 3.0.1, Abnormals Core 3.0.6).

Valhelsia dev here. Invisible mobs (with no hitbox) is an issue with OptiFine, and has been for quite a long time.

**Comment by InfinitysDaughter** [comment]
> > I'm having a... tangential problem, which might explain InfinitysDaughter's problem. They are spawning at a decent rate AFAICT but they are all invisible and seem to have no hurt boxes, resulting in me getting shaken to death repeatedly. Their sonar shows up but they don't even show up with F3+b(though the sonar does). Playing on the Valhesia 3 modpack, multiplayer, though I can't find any thrashers, invisible nor visible in singleplayer. (Upgrade Aquatic 3.0.1, Abnormals Core 3.0.6).
> 
> Valhelsia dev here. Invisible mobs (with no hitbox) is an issue with OptiFine, and has been for quite a long time.

Well then I can say thats not my issue. Dont have optifine at the moment. It was giving me other issues so I removed it until I've got other issues taken care of.

**Comment by Tiln1** [comment]
> > I'm having a... tangential problem, which might explain InfinitysDaughter's problem. They are spawning at a decent rate AFAICT but they are all invisible and seem to have no hurt boxes, resulting in me getting shaken to death repeatedly. Their sonar shows up but they don't even show up with F3+b(though the sonar does). Playing on the Valhesia 3 modpack, multiplayer, though I can't find any thrashers, invisible nor visible in singleplayer. (Upgrade Aquatic 3.0.1, Abnormals Core 3.0.6).
> 
> Valhelsia dev here. Invisible mobs (with no hitbox) is an issue with OptiFine, and has been for quite a long time.

Does Valhelsia 3 have OptiFine? I don't see it, and I didn't install it separately.

**Comment by bageldotjpg** [comment]
This is because their spawnrates are tuned for vanilla ocean depth, so mods that extend the ocean in some way shape or form are going to spawn way too many of them in the wrong places. There may be a more extensive config in the future but for now you can use something like InControl to modify their rates.
