### ISSUE TITLE
Crash on rendering bucket of box jellyfish

### ISSUE THREAD

**Issue by chadandersen1** [team-abnormals/upgrade-aquatic#242]
I suppose it is probably a mod conflict, but I can no longer join a world after trying to bucket a box jellyfish. I read in another issue that 1.15.2 was no longer being updated and I'm on the latest versions of the mod and core so I'll just edit it out of my inventory but just thought I'd put this here anyway. Any other known fix would be appreciated but I can catch the jellyfish in other things if not
[https://pastebin.com/HPhYVR0E](https://pastebin.com/HPhYVR0E)

**Comment by bageldotjpg** [comment]
Unfortunately, 1.15 is no longer supported
