### ISSUE TITLE
Mixin Crash w/ Physics Mod

### ISSUE THREAD

**Issue by WenXin20** [team-abnormals/upgrade-aquatic#244]
`Minecraft v1.16.5`
`Forge v36.0.13`
[`Physics v1.0.1`](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
`Upgrade Aquatic v3.0.1`

This mod causes a mixin crash with the drowned when the physics mod is installed. Is compat possible?
Also reported to https://www.curseforge.com/minecraft/mc-mods/physics-mod?page=3#c42
[Crash Report](https://gist.github.com/WenXin20/199b7736ad25add975b8ca1d707db874)

**Comment by SmellyModder** [comment]
Looks like the Physics mod is making `func_225621_a_()` public and not protected. This is an issue on their side.

**Comment by WenXin20** [comment]
Alright, thanks.

**Comment by WenXin20** [comment]
Is a config option possible to disable the drowned mixin? The author of physics is saying it requires the functionality of the vanilla mob. https://www.curseforge.com/minecraft/mc-mods/physics-mod#c148

**Comment by Brittank88** [comment]
Requesting the same thing. I'd like to play with both mods, even if it requires a compromise.
