### ISSUE TITLE
Blue & Purple Pickerelweed show up twice in the JEI Smoking category

### ISSUE THREAD

**Issue by TDarkShadow** [team-abnormals/upgrade-aquatic#253]
Minecraft: 1.16.5
Forge: 36.0.42
Abnormals Core: 1.16.4-3.0.6
Upgrade Aquatic: 1.16.5-3.0.1
Just Enough Items: 1.16.4-7.6.1.71

Minor bug, but both Blue and Purple Pickerelweed show up twice in the Smoking category of JEI.
They also both show different XP output.

![afbeelding](https://user-images.githubusercontent.com/5389859/108646353-d23c4580-74b5-11eb-8b49-82fc1052f26a.png)

**Comment by bageldotjpg** [comment]
Could you use F3+H and share the recipe IDs of each?

**Comment by TDarkShadow** [comment]
Ofcourse.
Blue Pickerelweed has 2 Smoker recipe ID's;
- upgrade_aquatic:boiled_blue_pickerelweed_from_smoker
- upgrade_aquatic:smoked_blue_weed
Purple Pickerelweed has also 2 Smoker recipe ID's;
- upgrade_aquatic:smoked_purp_weed
- upgrade_aquatic:boiled_purple_pickerelweed_from_smoker
