### ISSUE TITLE
Potion Description Compat Incorrect

### ISSUE THREAD

**Issue by IdrisQe** [team-abnormals/upgrade-aquatic#254]
I'm pretty certain the Potion Description compat is bugged out for Upgrade Aquatic, since the potion of Insomnia (being unable to sleep) describes itself as "resetting the timer so Phantoms don't spawn" while the potion of Restfulness (sleeping well) describes itself as "increasing the Insomnia timer, allowing Phantoms to spawn"... Which doesn't seem right at all.

**Comment by bageldotjpg** [comment]
Please report it to them, as that is done on their end
