### ISSUE TITLE
Fishing loot table overwrites other mods

### ISSUE THREAD

**Issue by KekLeon** [team-abnormals/upgrade-aquatic#257]
I installed both upgrade aquatic and aquaculture 2 (https://www.curseforge.com/minecraft/mc-mods/aquaculture), but the loot tables overwrite eachother, so you only get items from upgrade aquatic, and not aquaculture.

**Comment by Vylott** [comment]
I too am seeing this issue with Tombstone.  None of the Tombstone special drops from fishing occur when Upgrade Aquatic is installed.  I confirmed they still drop with only Abnormals Core installed.  I tested without Optifine as well and the only fished drops are from Upgrade Aquatic.
