### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Maikipl** [team-abnormals/upgrade-aquatic#258]
the side and top textures of the doors are missing

![Minecraft_ 1 16 5 - Tryb jednoosobowy 04 03 2021 10_56_00](https://user-images.githubusercontent.com/80037827/109948906-0e07b400-7cdb-11eb-9d01-ebdc69185980.png)

**Comment by bageldotjpg** [comment]
You seem to have an external resource pack modifying the door model
