### ISSUE TITLE
Alex's Mobs Compatibility [Spiked Turtle Shell Helmet]

### ISSUE THREAD

**Issue by HauntedSniper** [team-abnormals/upgrade-aquatic#268]
Alex's Mobs adds an upgrade for the turtle shell helmet, called the Spiked Turtle Shell Helmet, which lets you breathe underwater for longer, has more protection, knockback resistance, and all that stuff. It is a good upgrade from the vanilla turtle shell helmet.

However, since this mod reworked and improved the turtle shell helmet, I would like to suggest that the Spiked Turtle Shell Helmet from Alex's Mobs should work more like this mod's version of the turtle helmet than the vanilla turtle helmet.

**Comment by bageldotjpg** [comment]
This should be done on their end as it is not very viable for us to edit their helmet and would be much simpler for them to do that
