### ISSUE TITLE
Log spam: "Tried to add entity upgrade_aquatic:thrasher but it was marked as removed already"

### ISSUE THREAD

**Issue by Febilian** [team-abnormals/upgrade-aquatic#274]
When in a biome that is eligible for Thrasher spawning, the titular warning pops up in the log rather frequently. I do not know exactly why it's showing up or what it means, but it is probably unintended for it to be happening so often - thus I'm making this issue.

`Minecraft 1.16.5`
`Forge 36.1.4`
`abnormals_core-1.16.5-3.1.1`
`upgrade_aquatic-1.16.5-3.1.0`

**Comment by SmellyModder** [comment]
There isn't really much to work with here, as this a normal error that can happen with any entity for a variety of reasons.
It may be caused by an excessive amount of thrashers being in an area. Try lowering the spawn weight in the config.
