### ISSUE TITLE
Suggestion: compatibility with tetra

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [team-abnormals/upgrade-aquatic#277]
a few json files would make UA materials available for tetra tools. most notably:
- thrasher tooth should make a very good spearhead (worse than trident but better than most materials)
- prismarine rods should make finest light handles for spears

thanks

**Comment by SmellyModder** [comment]
Interesting suggestion.
This will probably not be something we'll ever add ourselves, but PRs are welcome.
