### ISSUE TITLE
Phantoms don't attack

### ISSUE THREAD

**Issue by TYPyz** [team-abnormals/upgrade-aquatic#282]
Several players in my modpack report that Phantoms do not attack players.
I investigated and realized that the Upgrade Aquatic is probably to blame.
To test this bug I removed various mods until this bug disappeared. It only disappeared once I removed the Upgrade Aquatic
[Here is a video of the phantoms behavior when Upgrade Aquatic is loaded](https://lowkey.gg/v/09b58d13-e7f2-439a-9302-b9fa428cc61d)
If you want to replicate the bug, just download the modpack [here](https://www.curseforge.com/minecraft/modpacks/create-an-empire-of-rats-to-fight-ice-and-fire)
wait 3 in-game days without sleep and on the third night the phantoms will spawn but will not attack you.
Then try to remove the Upgrade Aquatic mod and you will see that they will attack you.
_I also tested in a world made especially for testing and I wore nothing or had any active effects and the results are the same._
I hope this bug is fixed as soon as possible.

**Comment by SmellyModder** [comment]
Upgrade Aquatic makes it so Phantoms will only target players that are considered insomniacs.
Insomniacs being players that have not slept in over 1 hour (3 days in-game).
Therefore, it would make sense that the Phantoms aren't attacking you because you're not considered an insomniac.
