### ISSUE TITLE
Stunned Thrasher doesn't let you go

### ISSUE THREAD

**Issue by Sweehba** [team-abnormals/upgrade-aquatic#283]
I thought stunning a Thrasher while in it's mouth was supposed to cause it to let go of the player so you can escape / back off. However, this doesn't seem to work as it keeps you in it's mouth even when stunned. I heard someone mention it was a bug with optifine, but it still doesn't let go when optifine is turned off. Is this actually intended or is this a bug? Because the fact that you can't escape makes it almost impossible to survive a thrasher grab up untill you reach the end game.

**Comment by SmellyModder** [comment]
This is not intentional, but broke somehow during porting.
Fixed in 11697dc94d67407c699675d4a4672bef71cf0336

**Comment by Sweehba** [comment]
Is that going to be in the next update then? Or can I change this manually?
