### ISSUE TITLE
Consider making Thrasher sonar waves invisible at higher difficulty levels

### ISSUE THREAD

**Issue by diodelass** [team-abnormals/upgrade-aquatic#287]
I understand if this suggestion doesn't go over well, because it's clear that a lot of work was put into the visuals of Thrasher sonar and it would undoubtedly hurt to throw it out, even partially. However, I wanted to table this suggestion anyway just in case, because I think it would be really cool.

At the moment, it's pretty easy to tell when you've been detected by a Thrasher, because you can see the sonar wavefronts passing over you. However, since Thrashers are so fast and you're usually in a confined, deep-water space when you encounter one, my experience has been that there's not a lot that you can do to stop them from catching you once you've been detected. Apart from just equipping high-end armor and weapons to fight them off, it seems like the intended strategy is to avoid being detected in the first place, and while a visible detection cone does make this a lot easier to navigate, I can't help but wonder if it makes things a little too easy sometimes. In addition, I also feel like the moment of uncertainty and panic that would arise from seeing a Thrasher roar at you, darting out of the way, and then not being *quite* sure whether or not you moved fast enough would be a powerful and exciting effect. The short pause between a Thrasher emitting sonar and then deciding whether to pursue a target or turn away seems perfectly tuned for this already, and since your escape options are already limited after detection, I'm optimistic that this would still keep a decent balance without making everything too much more frustrating.

One problem I can foresee is that new players might have trouble understanding how Thrasher behavior works without the obvious sonar waves to help, but watching them attack other underwater mobs seems like it might still get the point across well enough. At any rate, it might still be a good fit for Hard difficulty either way.

It's fine if this suggestion proves unpopular, but since it comes to mind every time I play the game with this mod, I figured I'd share it here and see what the prevailing opinion is.

**Comment by SmellyModder** [comment]
Thanks for the suggestion 🙂 
I'm not exactly fond of this because I imagine many players getting attacked and not knowing why. It would also make first-time players on higher difficulties not understand the Thrasher's attack behavior.
Also, suggestions should be discussed on our Discord server if possible: https://discord.gg/abnormals
