### ISSUE TITLE
Bedroll gone when loading game?

### ISSUE THREAD

**Issue by Elmfeather7** [team-abnormals/upgrade-aquatic#290]
So, I have the latest version of this mod on 1.16.5, and the recommended version of forge, every time I load into the game, if I had a bedroll in my inventory it is gone. Even if it's placed it disappears.

**Comment by SmellyModder** [comment]
This is a strange issue. I'm not sure what could cause this from the mod.
I can't seem to reproduce this.
Does this occur when only Upgrade Aquatic is loaded?
