### ISSUE TITLE
[1.16.5-3.1.0] Bookshelves are not forge tagged

### ISSUE THREAD

**Issue by Rosethorns** [team-abnormals/upgrade-aquatic#294]
Upgrade Aquatic bookshelves should have the item tag forge:bookshelves

**Comment by SmellyModder** [comment]
Similar to the issue opened on Endergetic: https://github.com/team-abnormals/endergetic/issues/198
Forge does not have a `forge:bookshelves` block tag, and the Upgrade Aquatic bookshelves are in the `forge:bookshelves` item tag.
