### ISSUE TITLE
Pike AI issues

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/upgrade-aquatic#297]
A pike doesn't aggro you even after you punch it if it has an item in its mouth.

**Comment by SmellyModder** [comment]
This issue is pretty vague. Can you elaborate more?

**Comment by thelegitdolt** [comment]
righto, i'll record some videos after i get home from school

**Comment by thelegitdolt** [comment]
i'm pretty sure this is intended
After you punch a pike with a fish item in its mouth, the pikes completely ignores you, but if the pike has any other item, like bone meal, he'll go for you like usual.

**Comment by SmellyModder** [comment]
Yes, this is intentional as the Pike is considered _eating_ the fish item when it has a fish item in its mouth.
Although, we always consider changing a feature if it seems awkward.

**Comment by thelegitdolt** [comment]
knew it, thanks
