### ISSUE TITLE
New added fishes should be obtainable through fishing 

### ISSUE THREAD

**Issue by toffi3** [team-abnormals/upgrade-aquatic#304]
i tested it for a while and it seems that they are not obtainable this way. Is there any chance that new fishes will be obtainable this way?

**Comment by SmellyModder** [comment]
The new fish we added should currently be obtainable from fishing but are only catchable in specific biomes.
Make sure you are testing these conditions:
| Fish | Biomes |
| ------------- | ------------- |
| Pike | Swamps, Swamp Hills, and Rivers |
| Perch | Swamps and Swamp Hills |
| Lionfish | Warm Oceans and Deep Warm Oceans |

**Comment by toffi3** [comment]
Is there a way to change it by myself in the mod to have them in all biomes?

**Comment by toffi3** [comment]
Or i don't see a way to disable fisherman trades in the config, i think this should be a thing

**Comment by SmellyModder** [comment]
It is not currently possible to customize where the specific fish from this mod can get caught.
We are planning to make all the loot table modifications use JSON files to make them customizable.
We will consider adding a config option for the fisherman trades.
