### ISSUE TITLE
No love for regular oceans?

### ISSUE THREAD

**Issue by Boolyman** [team-abnormals/upgrade-aquatic#305]
Is there any way you could add some config options to get at least SOME of your features in regular Ocean and Deep Oceans?  Some plants, mobs, etc...

**Comment by thelegitdolt** [comment]
thrashers, glow squid, nautilus, lionfishes, and embedded ammonite are all ocean content lul

**Comment by SmellyModder** [comment]
There are many features from this mod that can be found in Ocean and Deep Ocean biomes.
We always consider more config options where we see appropriate.
