### ISSUE TITLE
Glowing Ink Sacs only apply to editing text

### ISSUE THREAD

**Issue by Reshy** [team-abnormals/upgrade-aquatic#308]
![2021-11-25_01 05 51](https://user-images.githubusercontent.com/2096384/143729101-43c21c4a-f254-4471-ad91-d1c11c95f417.png)

You can see in the screenshot that although the edit sign text has been brightened, the actual sign text is unchanged in it's brightness.

**Comment by SmellyModder** [comment]
I believe the screenshot you have given doesn't relate to the issue you are talking about.
Maybe you uploaded the wrong screenshot?

**Comment by Reshy** [comment]
Fixed it, I think.
