### ISSUE TITLE
Thrashers Make Cursor Unmovable with Optifine

### ISSUE THREAD

**Issue by alexblaauw** [team-abnormals/upgrade-aquatic#311]
When playing I discovered being caught by a thrasher caused my cursor/camera to become stuck entirely. After some experimenting I discovered this was the result of a compatibility issue with Optifine shaders, and turning my shaders off made it possible to move my cursor again and actually fight back rather than be doomed the second I got stuck in their maw. As far as I know this issue has existed for a while and persists even in the latest version of Upgrade Aquatic (3.1.1 as of the writing of this)

**Comment by bageldotjpg** [comment]
As Optifine is closed source and does many hacky things, it can not and will not be supported

**Comment by alexblaauw** [comment]
> As Optifine is closed source and does many hacky things, it can not and will not be supported
I didn't realize Optifine was closed source. Can't say I'm surprised, though 
Thanks anyway!
