### ISSUE TITLE
Wiki page or please add an actual detailed description of what your mods add.

### ISSUE THREAD

**Issue by darchitectlp** [team-abnormals/upgrade-aquatic#312]
This issue is for all the abnormals mods: I feel like I'm stuck in a loop... I click your "website" link on your curseforge page (that has almost no information) about your mods, only to land on your website, which then drives back to your pretty, but mostly empty, curseforge page. I don't want to have to dig through changelogs to see what your mods actually include. Any chance you all would consider actually adding some substantive details?

Or am I missing something here?

**Comment by SmellyModder** [comment]
We're sorry that you find it confusing to find information on our mods, but fortunately, we have recently started working on Wikis for all of our mods on our Github repositories.
Keep an eye out for updates to the Wiki pages on our repositories.
