### ISSUE TITLE
Configuration for Turtle Shell changes

### ISSUE THREAD

**Issue by Stormalisk** [team-abnormals/upgrade-aquatic#313]
In wanting to keep consistency with the Turtle Armor Mod and Better Diving for my modpack, I looked to see if there was configuration for the Vanilla Turtle Shell changes.
There is none to change the durability for breathing mechanic, however, so I was wondering if an option to change them could be added to the configuration.

**Comment by SmellyModder** [comment]
A config option to change this will get considered.
