### ISSUE TITLE
Issue causing fatal crash error on startup

### ISSUE THREAD

**Issue by wo11yy** [team-abnormals/upgrade-aquatic#316]
After extensive tests I know this mod is causing the error but I do not know why. It is a heavily modded pack, but when i add this one alone, it crashes. Here are my logs
[crash-2022-01-25_08.53.37-client.txt](https://github.com/team-abnormals/upgrade-aquatic/files/7934215/crash-2022-01-25_08.53.37-client.txt)
[latest.log](https://github.com/team-abnormals/upgrade-aquatic/files/7934217/latest.log)
.

**Comment by SmellyModder** [comment]
One of the mods you are using is changing the access of a `protected` method in code to `public`, which will break a mixin in this mod.
The method here is `func_225621_a_` -> `applyRotations`
I think the Physics mod might be causing it, so you could try removing it.
Generally, it is bad practice to access transform a `protected` method, which is what a mod is doing here.
