### ISSUE TITLE
Driftwood/tooth door rendering issue with resource pack

### ISSUE THREAD

**Issue by Sinuisan** [team-abnormals/upgrade-aquatic#317]
Ok so an odd one, and not critical. 

Running A Little Taste of Jerm resource pack, the Driftwood Door, Tooth Door and RiverWood door.  (double and single) are missing the lower half of the render on one side. Also appears when the door is 'open'. Does not appear on Trapdoors. 

Further, partially missing texture on Glassdoor, and GlassTrapdoor. Minor but possibly related. Attached image for reference as hard to describe. 

Not critical, but really odd. Cannot figure out why. Cant find a reference to your doors in the resource pack. Be nice to fix or at least point to so I can fix it. Any help appreciated.

 
![Inked2022-02-02_12 49 33_LI](https://user-images.githubusercontent.com/25729205/152157283-7732bead-d34a-4c31-bcce-28fbc375b6f0.jpg)

![2022-02-02_12 43 07](https://user-images.githubusercontent.com/25729205/152156057-8d3753d2-4614-4e3a-9d7f-4a6dbe76c85c.png)

![2022-02-02_12 49 33](https://user-images.githubusercontent.com/25729205/152156997-c463cc0c-2b6b-4902-8757-3ffb17910371.png)

Quark r.2.40321
Magnesium 1.5
Abnormals Core 1.16-3.3.1
Upgrade Aquatic 16.15-3.1.2
AutoRegLib-1.6-49

MC 1.16.5
Forge 32.2.20

**Comment by SmellyModder** [comment]
It's possible that _A Little Taste of Jerm_ could be modifying vanilla's door models, which is what the door models in this mod use.
Our doors use vanilla door models, so this is something that the dev of _A Little Taste of Jerm_ has to look into.
