### ISSUE TITLE
Bugs with textures and inhabitants

### ISSUE THREAD

**Issue by RIZ79** [team-abnormals/upgrade-aquatic#320]
1.16
upgrade_aquatic-1.16.5-3.1.2

Bugs with textures and inhabitants
Also because of the mod, dolphins and some other inhabitants from other mods will not spawn
Aquafina_no_pollution_1.0.0

![2022-02-19_11 16 38](https://user-images.githubusercontent.com/82448538/154795181-d1d9db21-35e9-4852-a92c-35a0a1691eeb.png)
![2022-02-19_11 14 13](https://user-images.githubusercontent.com/82448538/154795210-9a2efcb8-035d-42cf-8fdb-a7e93ec11c9b.png)

**Comment by SmellyModder** [comment]
The mob spawning issue must be an issue on Aquafina's side. The texture issues are definitely not our fault; we use vanilla's coral models.
